// ==================== VARIABLES ====================
// Set the load ID to use for group operations
@load_id = 

### Get OpenID configuration from Keycloak
GET {{authorization_host}}/realms/{{realm}}/.well-known/openid-configuration

### Authenticate to Keycloak and get a token
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&client_secret={{client_secret}}&username={{username}}&password={{password}}&scope=openid

### [TEST ONLY] Authenticate to Keycloak using UMA ticket grant (for advanced authorization testing)
# This call is for testing purposes only. It requests a token from Keycloak using the UMA ticket grant type,
# which is used for fine-grained authorization scenarios (RBAC).
# Spring Cloud Gateway is configured to do this automatically. Only used this if you need to call services directly.
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{Authenticate.response.body.access_token}}

grant_type=urn:ietf:params:oauth:grant-type:uma-ticket&client_id={{client_id}}&client_secret={{client_secret}}&audience={{client_id}}&scope=openid

### Get list of all groups
# @name GetGroups
GET {{api_gateway_host}}/api/groups/load/{{load_id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new group
# @name CreateGroup
POST {{api_gateway_host}}/api/groups
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "date": "2024-01-15",
  "loadId": "{{load_id}}",
  "powderCharge": 26.5,
  "targetRange": 100,
  "groupSize": 0.40
}

### Get group by ID
# @name GetGroupById
GET {{api_gateway_host}}/api/groups/{{CreateGroup.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Get group statistics
# @name GetGroupStats
GET {{api_gateway_host}}/api/groups/{{CreateGroup.response.body.id}}/statistics
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update group
# @name UpdateGroup
PUT {{api_gateway_host}}/api/groups/{{CreateGroup.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "date": "2024-01-15",
  "loadId": "{{load_id}}",
  "powderCharge": 28.0,
  "targetRange": 200,
  "groupSize": 0.50
}

### Delete group
# @name DeleteGroup
DELETE {{api_gateway_host}}/api/groups/{{CreateGroup.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}
