### Get OpenID configuration from Keycloak
GET {{authorization_host}}/realms/{{realm}}/.well-known/openid-configuration

### Authenticate to Keycloak and get a token
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&client_secret={{client_secret}}&username={{username}}&password={{password}}&scope=openid

### [TEST ONLY] Authenticate to Keycloak using UMA ticket grant (for advanced authorization testing)
# This call is for testing purposes only. It requests a token from Keycloak using the UMA ticket grant type,
# which is used for fine-grained authorization scenarios (RBAC).
# Spring Cloud Gateway is configured to do this automatically. Only used this if you need to call services directly.
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{Authenticate.response.body.access_token}}

grant_type=urn:ietf:params:oauth:grant-type:uma-ticket&client_id={{client_id}}&client_secret={{client_secret}}&audience={{client_id}}&scope=openid

### Get list of all rifles
# @name GetRifles
GET {{api_gateway_host}}/api/rifles
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new rifle (Imperial units - inches)
# @name CreateRifle
POST {{api_gateway_host}}/api/rifles
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Long Range Precision Rifle",
  "description": "6.5 Creedmoor bolt action rifle with precision barrel",
  "caliber": "6.5 Creedmoor",
  "barrelLength": {
    "value": 24.0,
    "unit": "[in_i]",
    "scale": "ABSOLUTE"
  },
  "barrelContour": "Heavy Varmint",
  "rifling": {
    "twistRate": {
      "value": 8.0,
      "unit": "[in_i]",
      "scale": "ABSOLUTE"
    },
    "twistDirection": "RIGHT",
    "numberOfGrooves": 5
  },
  "zeroing": {
    "sightHeight": {
      "value": 1.5,
      "unit": "[in_i]",
      "scale": "ABSOLUTE"
    },
    "zeroDistance": {
      "value": 100.0,
      "unit": "[yd_i]",
      "scale": "ABSOLUTE"
    }
  }
}

### Get created rifle by ID
# @name GetCreatedRifle
GET {{api_gateway_host}}/api/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update created rifle (Imperial units - inches)
# @name UpdateCreatedRifle
PUT {{api_gateway_host}}/api/rifles/{{CreateRifle.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Tikka T3x Custom",
  "description": "Tikka T3x with Bartlein barrel and MDT chassis",
  "caliber": "6mm Creedmoor",
  "barrelLength": {
    "value": 26.0,
    "unit": "[in_i]",
    "scale": "ABSOLUTE"
  },
  "barrelContour": "M24",
  "rifling": {
    "twistRate": {
      "value": 7.5,
      "unit": "[in_i]",
      "scale": "ABSOLUTE"
    },
    "twistDirection": "RIGHT",
    "numberOfGrooves": 6
  },
  "zeroing": {
    "sightHeight": {
      "value": 1.75,
      "unit": "[in_i]",
      "scale": "ABSOLUTE"
    },
    "zeroDistance": {
      "value": 200.0,
      "unit": "[yd_i]",
      "scale": "ABSOLUTE"
    }
  }
}

### Delete created rifle
# @name DeleteCreatedRifle
DELETE {{api_gateway_host}}/api/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a rifle with metric units (centimeters and millimeters)
# @name CreateRifleMetric
POST {{api_gateway_host}}/api/rifles
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "European Hunting Rifle",
  "description": "7x64mm Brenneke hunting rifle with metric specifications",
  "caliber": "7x64mm Brenneke",
  "barrelLength": {
    "value": 61.0,
    "unit": "cm",
    "scale": "ABSOLUTE"
  },
  "barrelContour": "Medium Sporter",
  "rifling": {
    "twistRate": {
      "value": 22.86,
      "unit": "cm",
      "scale": "ABSOLUTE"
    },
    "twistDirection": "RIGHT",
    "numberOfGrooves": 4
  },
  "zeroing": {
    "sightHeight": {
      "value": 4.0,
      "unit": "cm",
      "scale": "ABSOLUTE"
    },
    "zeroDistance": {
      "value": 100.0,
      "unit": "m",
      "scale": "ABSOLUTE"
    }
  }
}

### Get the metric rifle
GET {{api_gateway_host}}/api/rifles/{{CreateRifleMetric.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Delete metric rifle
DELETE {{api_gateway_host}}/api/rifles/{{CreateRifleMetric.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}
