### Get OpenID configuration from Keycloak
GET {{authorization_host}}/realms/{{realm}}/.well-known/openid-configuration

### Authenticate to Keycloak and get a token
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&client_secret={{client_secret}}&username={{username}}&password={{password}}&scope=openid

### Get list of all rifles
# @name GetRifles
GET http://localhost:8080/api/rifles/rifles
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new rifle
# @name CreateRifle
POST http://localhost:8080/api/rifles/rifles
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Savage 110 Elite Precision",
  "description": "Long range precision rifle with MDT chassis",
  "caliber": ".308 Winchester",
  "barrelLength": 24.0,
  "barrelLengthUnit": "INCHES",
  "barrelContour": "Medium Palma",
  "twistRate": "1:10",
  "freeBore": 0.160,
  "freeBoreUnit": "INCHES",
  "rifling": "6 Groove"
}

### Get created rifle by ID
# @name GetCreatedRifle
GET http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update created rifle
# @name UpdateCreatedRifle
PUT http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Tikka T3x Custom",
  "description": "Tikka T3x with Bartlein barrel and MDT chassis",
  "caliber": "6mm Creedmoor",
  "barrelLength": 26.0,
  "barrelLengthUnit": "INCHES",
  "barrelContour": "M24",
  "twistRate": "1:7.5",
  "freeBore": 0.153,
  "freeBoreUnit": "INCHES",
  "rifling": "6 Groove"
}

### Delete created rifle
# @name DeleteCreatedRifle
DELETE http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}
