### Get OpenID configuration from Keycloak
GET {{authorization_host}}/realms/{{realm}}/.well-known/openid-configuration

### Authenticate to Keycloak and get a token
# @name Authenticate
POST {{authorization_host}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{client_id}}&client_secret={{client_secret}}&username={{username}}&password={{password}}&scope=openid

// ==================== RIFLES ====================

### Get list of all rifles
# @name GetRifles
GET http://localhost:8080/api/rifles/rifles
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new rifle
# @name CreateRifle
POST http://localhost:8080/api/rifles/rifles
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Savage 110 Elite Precision",
  "description": "Long range precision rifle with MDT chassis",
  "caliber": ".308 Winchester",
  "barrelLength": 24.0,
  "barrelLengthUnit": "INCHES",
  "barrelContour": "Medium Palma",
  "twistRate": "1:10",
  "freeBore": 0.160,
  "freeBoreUnit": "INCHES",
  "rifling": "6 Groove"
}

### Get created rifle by ID
# @name GetCreatedRifle
GET http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update created rifle
# @name UpdateCreatedRifle
PUT http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Tikka T3x Custom",
  "description": "Tikka T3x with Bartlein barrel and MDT chassis",
  "caliber": "6mm Creedmoor",
  "barrelLength": 26.0,
  "barrelLengthUnit": "INCHES",
  "barrelContour": "M24",
  "twistRate": "1:7.5",
  "freeBore": 0.153,
  "freeBoreUnit": "INCHES",
  "rifling": "6 Groove"
}

### Delete created rifle
# @name DeleteCreatedRifle
DELETE http://localhost:8080/api/rifles/rifles/{{CreateRifle.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

// ==================== LOADS ====================

### Get list of all loads
# @name GetLoads
GET http://localhost:8080/api/loads/loads
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new load
# @name CreateLoad
POST http://localhost:8080/api/loads/loads
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "New Load",
  "description": "Description of the new load",
  "measurementUnits": "Imperial",
  "powderManufacturer": "Hodgdon",
  "powderType": "H335",
  "powderCharge": 25.0,
  "bulletManufacturer": "Hornady",
  "bulletType": "FMJ",
  "bulletWeight": 55,
  "primerManufacturer": "CCI",
  "primerType": "Small Rifle",
  "distanceFromLands": 0.02,
  "caseOverallLength": 2.260,
  "neckTension": 0.002,
  "rifleId": 1
}

### Get the created load by ID
# @name GetLoadById
GET http://localhost:8080/api/loads/loads/{{CreateLoad.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Get load statistics
# @name GetLoadStats
GET http://localhost:8080/api/loads/loads/{{CreateLoad.response.body.id}}/statistics
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update the created load
# @name UpdateLoad
PUT http://localhost:8080/api/loads/loads/{{CreateLoad.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "name": "Updated Load",
  "description": "Updated description of the load",
  "measurementUnits": "Imperial",
  "powderManufacturer": "IMR",
  "powderType": "4064",
  "powderCharge": 42.0,
  "bulletManufacturer": "Sierra",
  "bulletType": "HPBT",
  "bulletWeight": 168,
  "primerManufacturer": "Federal",
  "primerType": "Large Rifle",
  "distanceFromLands": 0.03,
  "caseOverallLength": 2.800,
  "neckTension": 0.003,
  "rifleId": 2
}

### Delete the created load
# @name DeleteLoad
DELETE http://localhost:8080/api/loads/loads/{{CreateLoad.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

// ==================== GROUPS ====================

### Get list of all groups
# @name GetGroups
GET http://localhost:8080/api/loads/groups/load/{{CreateLoad.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new group
# @name CreateGroup
POST http://localhost:8080/api/loads/groups
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "date": "2024-01-15",
  "loadId": "{{CreateLoad.response.body.id}}",
  "powderCharge": 26.5,
  "targetRange": 100,
  "groupSize": 0.40
}

### Get group by ID
# @name GetGroupById
GET http://localhost:8080/api/loads/groups/{{CreateGroup.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Get group statistics
# @name GetGroupStats
GET http://localhost:8080/api/loads/groups/{{CreateGroup.response.body.id}}/statistics
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update group
# @name UpdateGroup
PUT http://localhost:8080/api/loads/groups/{{CreateGroup.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "date": "2024-01-15",
  "loadId": "{{CreateLoad.response.body.id}}",
  "powderCharge": 28.0,
  "targetRange": 200,
  "groupSize": 0.50
}

### Delete group
# @name DeleteGroup
DELETE http://localhost:8080/api/loads/groups/{{CreateGroup.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

// ==================== SHOTS ====================

### Get all shots for a group
# @name GetShots
GET http://localhost:8080/api/loads/shots/group/{{CreateGroup.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Create a new shot
# @name CreateShot
POST http://localhost:8080/api/loads/shots
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "groupId": "{{CreateGroup.response.body.id}}",
  "velocity": 2800
}

### Get shot by ID
# @name GetShotById
GET http://localhost:8080/api/loads/shots/{{CreateShot.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

### Update shot
# @name UpdateShot
PUT http://localhost:8080/api/loads/shots/{{CreateShot.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{Authenticate.response.body.access_token}}

{
  "groupId": "{{CreateGroup.response.body.id}}",
  "velocity": 2850
}

### Delete shot
# @name DeleteShot  
DELETE http://localhost:8080/api/loads/shots/{{CreateShot.response.body.id}}
Authorization: Bearer {{Authenticate.response.body.access_token}}

