spring:
  application:
    name: components-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

---
spring:
  config:
    activate:
      on-profile: kubernetes
    import: "kubernetes:"
  cloud:
    config:
      enabled: false
    kubernetes:
      config:
        sources:
          - name: common-config
          - name: components-service-config
      discovery:
        all-namespaces: true
