spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles: 
    active: @spring.profiles.active@
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    refresh:
      enabled: false