spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  profiles: 
    active: @spring.profiles.active@
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
---
spring:
  config:
    activate:
      on-profile: native
  cloud:
    refresh:
      enabled: false