{{- if .Values.apiGateway.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-load-development.fullname" . }}-api-gateway
  namespace: {{ .Values.apiGateway.namespace | default "default" }}
  labels:
    {{- include "spring-load-development.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  replicas: {{ .Values.apiGateway.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "spring-load-development.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        {{- include "spring-load-development.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api-gateway
    spec:
      serviceAccountName: {{ include "spring-load-development.serviceAccountName" . }}
      containers:
      - name: api-gateway
        image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_APPLICATION_NAME
          value: "api-gateway"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otelCollector.grpcEndpoint | default "http://otel-collector-service.observability.svc.cluster.local:4317" }}
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: KEYCLOAK_BASE_URL
          value: {{ .Values.keycloak.integration.baseUrl | default "http://keycloak-service.keycloak.svc.cluster.local:8080" }}
        {{- if .Values.apiGateway.env }}
        {{- toYaml .Values.apiGateway.env | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: log4j2-volume
          mountPath: /etc/config
          readOnly: true
        resources:
          {{- toYaml .Values.apiGateway.resources | nindent 10 }}
      volumes:
      - name: log4j2-volume
        configMap:
          name: log4j2-config
      {{- with .Values.apiGateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiGateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.apiGateway.namespace | default "default" }}
  labels:
    {{- include "spring-load-development.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.apiGateway.service.port | default 8080 }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq (.Values.apiGateway.service.type | default "ClusterIP") "NodePort") .Values.apiGateway.service.nodePort }}
    nodePort: {{ .Values.apiGateway.service.nodePort }}
    {{- end }}
  selector:
    {{- include "spring-load-development.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway

{{- if .Values.apiGateway.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-load-development.fullname" . }}-api-gateway
  namespace: {{ .Values.apiGateway.namespace | default "default" }}
  labels:
    {{- include "spring-load-development.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with .Values.apiGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiGateway.ingress.tls }}
  tls:
    {{- range .Values.apiGateway.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.apiGateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "spring-load-development.fullname" $ }}-api-gateway
                port:
                  number: {{ $.Values.apiGateway.service.port | default 8080 }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}