{{- if .Values.mcpServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-load-development.fullname" . }}-mcp-server
  namespace: {{ .Values.microservices.namespace | default "reloading" }}
  labels:
    {{- include "spring-load-development.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  replicas: {{ .Values.mcpServer.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "spring-load-development.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        {{- include "spring-load-development.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      serviceAccountName: {{ include "spring-load-development.serviceAccountName" . }}
      containers:
      - name: mcp-server
        image: {{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SPRING_APPLICATION_NAME
          value: "mcp-server"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.otelCollector.grpcEndpoint | default "http://otel-collector-service.observability.svc.cluster.local:4317" }}
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: KEYCLOAK_BASE_URL
          value: {{ .Values.keycloak.integration.baseUrl | default "http://keycloak-service.keycloak.svc.cluster.local:8080" }}
        {{- if .Values.mcpServer.env }}
        {{- toYaml .Values.mcpServer.env | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: log4j2-volume
          mountPath: /etc/config
          readOnly: true
        resources:
          {{- toYaml .Values.mcpServer.resources | nindent 10 }}
      volumes:
      - name: log4j2-volume
        configMap:
          name: log4j2-config
      {{- with .Values.mcpServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  namespace: {{ .Values.microservices.namespace | default "reloading" }}
  labels:
    {{- include "spring-load-development.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  type: {{ .Values.mcpServer.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.mcpServer.service.port | default 8083 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "spring-load-development.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
{{- end }}