{{- if .Values.app.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.app.namespace }}
  labels:
    name: {{ .Values.app.namespace }}
    {{- include "spring-load-development.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.postgresql.namespace }}
  labels:
    name: {{ .Values.postgresql.namespace }}
    {{- include "spring-load-development.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.keycloak.namespace }}
  labels:
    name: {{ .Values.keycloak.namespace }}
    {{- include "spring-load-development.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.observability.namespace }}
  labels:
    name: {{ .Values.observability.namespace }}
    {{- include "spring-load-development.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.apiGateway.namespace }}
  labels:
    name: {{ .Values.apiGateway.namespace }}
    {{- include "spring-load-development.labels" . | nindent 4 }}
{{- end }}
