receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - IsMatch(span.attributes["http.url"], ".*actuator.*")
        - IsMatch(span.attributes["http.route"], ".*actuator.*")
  resource:
    attributes:
      - key: service.environment
        value: docker
        action: insert
      - key: service.version
        from_attribute: service_version
        action: insert

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: "0.0.0.0:8889"
  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [filter/ottl, resource, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]