receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 15s
  filter/ottl:
    error_mode: ignore
    traces:
      span:
        - IsMatch(span.attributes["http.url"], ".*actuator.*")
        - IsMatch(span.attributes["http.route"], ".*actuator.*")
        - kind.string == "Internal"
  resource:
    attributes:
      - key: service.environment
        value: docker
        action: insert
      - key: service.version
        from_attribute: service_version
        action: insert
      - key: service.name
        from_attribute: service.name
        action: upsert

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  zpages:
    endpoint: :55679

exporters:
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  otlphttp:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true
  debug:
    verbosity: detailed

service:
  extensions: [zpages,health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [filter/ottl, resource, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]